INSERT INTO users (firstname, lastname, username, password, email, userType, bio, jobTitle, career_interest, points)
VALUES 
    ('John', 'Doe', 'mentor_user1', 'password123', 'mentor1@example.com', 'mentor', 'Experienced mentor in software engineering.', 'Software Engineer', 'Software Engineer', 0),
    ('Jane', 'Smith', 'mentor_user2', 'password123', 'mentor2@example.com', 'mentor', 'Specialized in digital marketing strategies.', 'Marketing Manager', 'Digital Marketing Specialist', 0),
    ('James', 'Brown', 'mentor_user3', 'password123', 'mentor3@example.com', 'mentor', 'Helping others excel in operations management.', 'Operations Consultant', 'Operations Manager', 0),
    ('Emily', 'White', 'mentor_user4', 'password123', 'mentor4@example.com', 'mentor', 'Passionate mentor for UI/UX design.', 'UX Designer', 'UX/UI Designer', 0),
    ('Michael', 'Green', 'mentor_user5', 'password123', 'mentor5@example.com', 'mentor', 'Senior developer guiding junior engineers.', 'Senior Developer', 'Software Developer', 0),
    ('Laura', 'Johnson', 'mentor_user6', 'password123', 'mentor6@example.com', 'mentor', 'Focused on guiding aspiring project managers.', 'Project Consultant', 'Project Manager', 0),
    ('Robert', 'Miller', 'mentor_user7', 'password123', 'mentor7@example.com', 'mentor', 'Experienced in financial analysis and strategy.', 'Financial Advisor', 'Financial Analyst', 0),
    ('Sarah', 'Davis', 'mentor_user8', 'password123', 'mentor8@example.com', 'mentor', 'Dedicated to helping teachers improve.', 'Education Consultant', 'Teacher', 0),
    ('Daniel', 'Garcia', 'mentor_user9', 'password123', 'mentor9@example.com', 'mentor', 'Specialist in QA and testing methodologies.', 'QA Lead', 'QA Analyst', 0),
    ('Jessica', 'Martinez', 'mentor_user10', 'password123', 'mentor10@example.com', 'mentor', 'Expert in mechanical engineering solutions.', 'Mechanical Engineer', 'Mechanical Engineer', 0),
    ('Charles', 'Moore', 'mentor_user11', 'password123', 'mentor11@example.com', 'mentor', 'Guiding software developers towards excellence.', 'Software Architect', 'Software Architect', 0),
    ('Patricia', 'Hall', 'mentor_user12', 'password123', 'mentor12@example.com', 'mentor', 'Helping individuals transition into digital marketing.', 'Marketing Specialist', 'Digital Marketing Specialist', 0),
    ('David', 'Lopez', 'mentor_user13', 'password123', 'mentor13@example.com', 'mentor', 'Specialized in managing operations and teams.', 'Operations Manager', 'Operations Manager', 0),
    ('Jennifer', 'Gonzalez', 'mentor_user14', 'password123', 'mentor14@example.com', 'mentor', 'Experienced UX designer mentoring future designers.', 'UX Designer', 'UX/UI Designer', 0),
    ('Joseph', 'Harris', 'mentor_user15', 'password123', 'mentor15@example.com', 'mentor', 'Senior event planner guiding new professionals.', 'Event Manager', 'Event Manager', 0),
    ('Barbara', 'Clark', 'mentor_user16', 'password123', 'mentor16@example.com', 'mentor', 'Providing mentorship in electrical engineering.', 'Electrical Engineer', 'Electrical Engineer', 0),
    ('Thomas', 'Lewis', 'mentor_user17', 'password123', 'mentor17@example.com', 'mentor', 'Passionate about database administration.', 'Database Administrator', 'Database Administrator', 0),
    ('Susan', 'Robinson', 'mentor_user18', 'password123', 'mentor18@example.com', 'mentor', 'Helping others master financial planning.', 'Financial Advisor', 'Financial Planner', 0),
    ('Matthew', 'Walker', 'mentor_user19', 'password123', 'mentor19@example.com', 'mentor', 'Expert in urban and environmental planning.', 'Urban Planner', 'Urban Planner', 0),
    ('Nancy', 'Allen', 'mentor_user20', 'password123', 'mentor20@example.com', 'mentor', 'Mentoring new talent in social media management.', 'Social Media Manager', 'Social Media Manager', 0),
    ('Mark', 'Young', 'mentor_user21', 'password123', 'mentor21@example.com', 'mentor', 'Providing guidance in software testing.', 'QA Engineer', 'Software Tester', 0),
    ('Sarah', 'King', 'mentor_user22', 'password123', 'mentor22@example.com', 'mentor', 'Focused on career growth in customer service.', 'Customer Service Manager', 'Customer Service Manager', 0),
    ('Christopher', 'Wright', 'mentor_user23', 'password123', 'mentor23@example.com', 'mentor', 'Experienced investment banker mentoring others.', 'Investment Banker', 'Investment Banker', 0),
    ('Jessica', 'Scott', 'mentor_user24', 'password123', 'mentor24@example.com', 'mentor', 'Helping aspiring architects achieve their dreams.', 'Architect', 'Architect', 0),
    ('Daniel', 'Torres', 'mentor_user25', 'password123', 'mentor25@example.com', 'mentor', 'Sharing insights on systems engineering.', 'Systems Engineer', 'Systems Engineer', 0),
    ('Lisa', 'Nguyen', 'mentor_user26', 'password123', 'mentor26@example.com', 'mentor', 'Guiding aspiring nurses in their careers.', 'Nurse Manager', 'Nurse Practitioner', 0),
    ('Paul', 'Martinez', 'mentor_user27', 'password123', 'mentor27@example.com', 'mentor', 'Experienced in quality assurance.', 'QA Analyst', 'Quality Assurance Analyst', 0),
    ('Karen', 'Perez', 'mentor_user28', 'password123', 'mentor28@example.com', 'mentor', 'Helping marketers refine their strategies.', 'Marketing Director', 'Marketing Director', 0),
    ('Steven', 'Adams', 'mentor_user29', 'password123', 'mentor29@example.com', 'mentor', 'Specialist in chemical engineering solutions.', 'Chemical Engineer', 'Chemical Engineer', 0),
    ('Maria', 'Baker', 'mentor_user30', 'password123', 'mentor30@example.com', 'mentor', 'Guiding students in physical therapy careers.', 'Physical Therapist', 'Physical Therapist', 0),
    ('James', 'Carter', 'mentor_user31', 'password123', 'mentor31@example.com', 'mentor', 'Mentoring data scientists of the future.', 'Data Scientist', 'Data Scientist', 0),
    ('Linda', 'Phillips', 'mentor_user32', 'password123', 'mentor32@example.com', 'mentor', 'Expert in legal advising and contracts.', 'Legal Counsel', 'Legal Advisor', 0),
    ('George', 'Evans', 'mentor_user33', 'password123', 'mentor33@example.com', 'mentor', 'Sharing knowledge in supply chain management.', 'Supply Chain Manager', 'Supply Chain Manager', 0),
    ('Sandra', 'Edwards', 'mentor_user34', 'password123', 'mentor34@example.com', 'mentor', 'Helping teachers refine classroom strategies.', 'Teacher Trainer', 'Teacher', 0),
    ('Kevin', 'Collins', 'mentor_user35', 'password123', 'mentor35@example.com', 'mentor', 'Passionate about network engineering solutions.', 'Network Engineer', 'Network Engineer', 0),
    ('Elizabeth', 'Stewart', 'mentor_user36', 'password123', 'mentor36@example.com', 'mentor', 'Guiding creative professionals in graphic design.', 'Graphic Designer', 'Graphic Designer', 0),
    ('Brian', 'Reed', 'mentor_user37', 'password123', 'mentor37@example.com', 'mentor', 'Expert in email marketing strategies.', 'Marketing Specialist', 'Email Marketing Specialist', 0),
    ('Deborah', 'Rogers', 'mentor_user38', 'password123', 'mentor38@example.com', 'mentor', 'Experienced in inventory and procurement.', 'Procurement Manager', 'Procurement Manager', 0),
    ('Frank', 'Morgan', 'mentor_user39', 'password123', 'mentor39@example.com', 'mentor', 'Experienced event planner and consultant.', 'Event Planner', 'Event Planner', 0),
    ('Carol', 'Bell', 'mentor_user40', 'password123', 'mentor40@example.com', 'mentor', 'Guiding software developers in backend systems.', 'Back-End Developer', 'Back-End Developer', 0),
    ('Eric', 'Murphy', 'mentor_user41', 'password123', 'mentor41@example.com', 'mentor', 'Specialized in architectural design mentoring.', 'Architectural Designer', 'Architectural Designer', 0),
    ('Melissa', 'Bailey', 'mentor_user42', 'password123', 'mentor42@example.com', 'mentor', 'Helping students navigate structural engineering.', 'Structural Engineer', 'Structural Engineer', 0),
    ('Timothy', 'Rivera', 'mentor_user43', 'password123', 'mentor43@example.com', 'mentor', 'Sharing expertise in IT support.', 'IT Support Specialist', 'IT Support Specialist', 0),
    ('Amy', 'Cooper', 'mentor_user44', 'password123', 'mentor44@example.com', 'mentor', 'Experienced in market analysis and research.', 'Market Research Analyst', 'Market Research Analyst', 0),
    ('Jason', 'Richardson', 'mentor_user45', 'password123', 'mentor45@example.com', 'mentor', 'Guiding new professionals in social work.', 'Social Worker', 'Social Worker', 0),
    ('Michelle', 'Cox', 'mentor_user46', 'password123', 'mentor46@example.com', 'mentor', 'Experienced mentor in Java development.', 'Java Developer', 'Java Developer', 0),
    ('Ronald', 'Howard', 'mentor_user47', 'password123', 'mentor47@example.com', 'mentor', 'Passionate about coaching sales associates.', 'Sales Manager', 'Sales Associate', 0),
    ('Sharon', 'Ward', 'mentor_user48', 'password123', 'mentor48@example.com', 'mentor', 'Providing mentorship in tax consulting.', 'Tax Consultant', 'Tax Consultant', 0),
    ('Anthony', 'Torres', 'mentor_user49', 'password123', 'mentor49@example.com', 'mentor', 'Expert in environmental engineering.', 'Environmental Engineer', 'Environmental Engineer', 0),
    ('Donna', 'Peterson', 'mentor_user50', 'password123', 'mentor50@example.com', 'mentor', 'Helping graphic designers reach their potential.', 'Art Director', 'Graphic Designer', 0),
    ('Anna', 'Taylor', 'mentee_user1', 'password123', 'mentee1@example.com', 'mentee', 'Aspiring web developer looking for guidance.', 'Student', 'Web Developer', 0),
    ('Chris', 'Johnson', 'mentee_user2', 'password123', 'mentee2@example.com', 'mentee', 'Keen learner in the field of data analytics.', 'Intern', 'Data Analyst', 0),
    ('Sophia', 'Lee', 'mentee_user3', 'password123', 'mentee3@example.com', 'mentee', 'Exploring a career in marketing.', 'Junior Marketer', 'Marketing Specialist', 0),
    ('Ryan', 'Martinez', 'mentee_user4', 'password123', 'mentee4@example.com', 'mentee', 'Interested in cloud computing opportunities.', 'IT Trainee', 'IT Support Specialist', 0),
    ('Olivia', 'Garcia', 'mentee_user5', 'password123', 'mentee5@example.com', 'mentee', 'I am looking for guidance in cybersecurity.', 'Cybersecurity Intern', 'Network Security Specialist', 0),
    ('Liam', 'Hernandez', 'mentee_user6', 'password123', 'mentee6@example.com', 'mentee', 'Interested in architectural design.', 'Architectural Intern', 'Architectural Designer', 0),
    ('Emma', 'Clark', 'mentee_user7', 'password123', 'mentee7@example.com', 'mentee', 'Aspiring nurse practitioner.', 'Nursing Student', 'Nurse Practitioner', 0),
    ('Ethan', 'Walker', 'mentee_user8', 'password123', 'mentee8@example.com', 'mentee', 'Exploring possibilities in urban planning.', 'Urban Planning Trainee', 'Urban Planner', 0),
    ('Mia', 'Allen', 'mentee_user9', 'password123', 'mentee9@example.com', 'mentee', 'Excited to learn about environmental consulting.', 'Intern', 'Environmental Consultant', 0),
    ('Lucas', 'Young', 'mentee_user10', 'password123', 'mentee10@example.com', 'mentee', 'Looking to build a career in mechanical design.', 'Student', 'Mechanical Designer', 0),
    ('Sophia', 'Morgan', 'mentee_user11', 'password123', 'mentee11@example.com', 'mentee', 'Passionate about graphic design and branding.', 'Design Student', 'Graphic Designer', 0),
    ('William', 'Clark', 'mentee_user12', 'password123', 'mentee12@example.com', 'mentee', 'Excited to explore backend development opportunities.', 'Software Intern', 'Back-End Developer', 0),
    ('Emma', 'Reed', 'mentee_user13', 'password123', 'mentee13@example.com', 'mentee', 'Looking for mentorship in environmental consulting.', 'Intern', 'Environmental Consultant', 0),
    ('Liam', 'Bennett', 'mentee_user14', 'password123', 'mentee14@example.com', 'mentee', 'Aspiring financial analyst seeking guidance.', 'Finance Trainee', 'Financial Analyst', 0),
    ('Olivia', 'Phillips', 'mentee_user15', 'password123', 'mentee15@example.com', 'mentee', 'Interested in a career in architecture.', 'Architecture Student', 'Architect', 0),
    ('James', 'Murphy', 'mentee_user16', 'password123', 'mentee16@example.com', 'mentee', 'Learning about IT administration and support.', 'IT Intern', 'IT Support Specialist', 0),
    ('Isabella', 'Hughes', 'mentee_user17', 'password123', 'mentee17@example.com', 'mentee', 'Exploring digital marketing opportunities.', 'Marketing Intern', 'Digital Marketing Specialist', 0),
    ('Benjamin', 'Foster', 'mentee_user18', 'password123', 'mentee18@example.com', 'mentee', 'Aspiring nurse practitioner looking for guidance.', 'Nursing Student', 'Nurse Practitioner', 0),
    ('Mia', 'Gonzalez', 'mentee_user19', 'password123', 'mentee19@example.com', 'mentee', 'Excited to work on event management projects.', 'Event Coordinator Intern', 'Event Manager', 0),
    ('Lucas', 'Harris', 'mentee_user20', 'password123', 'mentee20@example.com', 'mentee', 'Interested in mastering data analytics.', 'Data Analyst Intern', 'Data Analyst', 0),
    ('Ava', 'Alexander', 'mentee_user21', 'password123', 'mentee21@example.com', 'mentee', 'Passionate about developing front-end web interfaces.', 'Frontend Intern', 'Front-End Developer', 0),
    ('Elijah', 'Perry', 'mentee_user22', 'password123', 'mentee22@example.com', 'mentee', 'Learning about procurement and supply chain.', 'Procurement Intern', 'Procurement Manager', 0),
    ('Charlotte', 'Cox', 'mentee_user23', 'password123', 'mentee23@example.com', 'mentee', 'Aspiring email marketing specialist.', 'Marketing Intern', 'Email Marketing Specialist', 0),
    ('Ethan', 'Ward', 'mentee_user24', 'password123', 'mentee24@example.com', 'mentee', 'Exploring the world of social media management.', 'Social Media Intern', 'Social Media Manager', 0),
    ('Amelia', 'Howard', 'mentee_user25', 'password123', 'mentee25@example.com', 'mentee', 'Looking to become a database administrator.', 'IT Intern', 'Database Administrator', 0),
    ('Logan', 'Price', 'mentee_user26', 'password123', 'mentee26@example.com', 'mentee', 'Learning about technical writing for IT.', 'Technical Writing Intern', 'Technical Writer', 0),
    ('Harper', 'Richardson', 'mentee_user27', 'password123', 'mentee27@example.com', 'mentee', 'Aspiring environmental engineer.', 'Engineering Student', 'Environmental Engineer', 0),
    ('Henry', 'Ross', 'mentee_user28', 'password123', 'mentee28@example.com', 'mentee', 'Exploring a career in tax consulting.', 'Finance Intern', 'Tax Consultant', 0),
    ('Abigail', 'Peterson', 'mentee_user29', 'password123', 'mentee29@example.com', 'mentee', 'Interested in learning about operations management.', 'Management Intern', 'Operations Manager', 0),
    ('Alexander', 'Sanchez', 'mentee_user30', 'password123', 'mentee30@example.com', 'mentee', 'Passionate about network engineering.', 'IT Intern', 'Network Engineer', 0),
    ('Emily', 'Henderson', 'mentee_user31', 'password123', 'mentee31@example.com', 'mentee', 'Excited to learn more about brand management.', 'Marketing Intern', 'Brand Manager', 0),
    ('Jack', 'Coleman', 'mentee_user32', 'password123', 'mentee32@example.com', 'mentee', 'Looking to grow as a sales consultant.', 'Sales Intern', 'Sales Consultant', 0),
    ('Ella', 'Bryant', 'mentee_user33', 'password123', 'mentee33@example.com', 'mentee', 'Keen to understand software architecture.', 'Software Intern', 'Software Architect', 0),
    ('Oliver', 'Bailey', 'mentee_user34', 'password123', 'mentee34@example.com', 'mentee', 'Aspiring psychologist interested in mental health.', 'Psychology Student', 'Psychologist', 0),
    ('Avery', 'Watson', 'mentee_user35', 'password123', 'mentee35@example.com', 'mentee', 'Learning about investment banking.', 'Finance Intern', 'Investment Banker', 0),
    ('Sebastian', 'Hayes', 'mentee_user36', 'password123', 'mentee36@example.com', 'mentee', 'Passionate about UI/UX research.', 'Design Intern', 'UX Researcher', 0),
    ('Chloe', 'Hughes', 'mentee_user37', 'password123', 'mentee37@example.com', 'mentee', 'Exploring speech therapy practices.', 'Speech Therapy Student', 'Speech Therapist', 0),
    ('Liam', 'Brooks', 'mentee_user38', 'password123', 'mentee38@example.com', 'mentee', 'Excited to learn about procurement processes.', 'Procurement Intern', 'Procurement Coordinator', 0),
    ('Aiden', 'Russell', 'mentee_user39', 'password123', 'mentee39@example.com', 'mentee', 'Keen to explore the world of content writing.', 'Content Writing Intern', 'Content Writer', 0),
    ('Scarlett', 'Wood', 'mentee_user40', 'password123', 'mentee40@example.com', 'mentee', 'Interested in urban planning and design.', 'Urban Planner Intern', 'Urban Planner', 0),
    ('Mason', 'Cruz', 'mentee_user41', 'password123', 'mentee41@example.com', 'mentee', 'Looking to master front-end engineering.', 'Frontend Engineer Intern', 'Front-End Engineer', 0),
    ('Grace', 'Rivera', 'mentee_user42', 'password123', 'mentee42@example.com', 'mentee', 'Learning about network administration.', 'IT Intern', 'Network Administrator', 0),
    ('Lucas', 'Cooper', 'mentee_user43', 'password123', 'mentee43@example.com', 'mentee', 'Aspiring to become a legal advisor.', 'Law Student', 'Legal Advisor', 0),
    ('Ella', 'Perry', 'mentee_user44', 'password123', 'mentee44@example.com', 'mentee', 'Interested in structural engineering.', 'Engineering Student', 'Structural Engineer', 0),
    ('Noah', 'Griffin', 'mentee_user45', 'password123', 'mentee45@example.com', 'mentee', 'Passionate about becoming a marketing analyst.', 'Marketing Intern', 'Marketing Analyst', 0),
    ('Lily', 'Foster', 'mentee_user46', 'password123', 'mentee46@example.com', 'mentee', 'Looking to grow in landscape architecture.', 'Architecture Intern', 'Landscape Architect', 0),
    ('Ethan', 'Flores', 'mentee_user47', 'password123', 'mentee47@example.com', 'mentee', 'Keen to explore IT administration.', 'IT Intern', 'IT Administrator', 0),
    ('Victoria', 'Morris', 'mentee_user48', 'password123', 'mentee48@example.com', 'mentee', 'Excited to start a career in art direction.', 'Design Intern', 'Art Director', 0),
    ('Samuel', 'Long', 'mentee_user49', 'password123', 'mentee49@example.com', 'mentee', 'Learning about email marketing techniques.', 'Marketing Intern', 'Email Marketing Specialist', 0),
    ('Avery', 'Harrison', 'mentee_user50', 'password123', 'mentee50@example.com', 'mentee', 'Aspiring to become a software tester.', 'QA Intern', 'Software Tester', 0);